function results = GTmaps_format(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

if(size(im, 3)~=3 && size(im, 1) ~= 224 && size(im, 2) ~= 224)
    % Resize ground truth image
    im_resize = imresize(im, [224, 224]);
    im_3d = cat(3, im_resize, im_resize, im_resize);
    im_gray = rgb2gray(im_3d);
    im_bw = imbinarize(im_gray);
    im_bw_3d = cat(3, im_bw, im_bw, im_bw);
    im_uint8 = im2uint8(im_bw_3d);
    %imwrite

else
    im_uint8 = im;
end

results.GTmaps_format = im_uint8;

%--------------------------------------------------------------------------
